import type { Metadata } from "next";
import { Geist, Geist_Mono,Poppins,Bricolage_Grotesque } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  weight: ["400", "700",],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const bricolageGrotesque = Bricolage_Grotesque({
  weight: ["400", "700","200", "300", "500", "600", "800"],
  subsets: ["latin"],
  variable: "--font-bricolage-grotesque",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preload hero images for faster loading */}
        <link rel="preload" href="/heero.svg" as="image" />
        <link rel="preload" href="/robott.svg" as="image" />
        <link rel="preload" href="/whatsappp.svg" as="image" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${bricolageGrotesque.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
